import { useGLTF } from "@react-three/drei";

useGLTF.preload("assets/models/boss.glb");
useGLTF.preload("assets/models/enemyMachineGunHead.glb");
useGLTF.preload("assets/models/enemyPistolHead.glb");
useGLTF.preload("assets/models/enemySword.glb");
useGLTF.preload("assets/models/enemySwordBody.glb");
useGLTF.preload("assets/models/enemySwordHead.glb");
useGLTF.preload("assets/models/enemyWizardBody.glb");
useGLTF.preload("assets/models/enemyWizardHead.glb");
useGLTF.preload("assets/models/knightBody.glb");
useGLTF.preload("assets/models/knightGun.glb");
useGLTF.preload("assets/models/knightHead.glb");
useGLTF.preload("assets/models/knightPlayer.glb");
useGLTF.preload("assets/models/machineGun.glb");
useGLTF.preload("assets/models/machineGunBarrel.glb");
useGLTF.preload("assets/models/machineGunBody.glb");
useGLTF.preload("assets/models/mainMenuModel.glb");
useGLTF.preload("assets/models/modelEnemySwordHead.glb");
useGLTF.preload("assets/models/playerAfterImage.glb");
useGLTF.preload("assets/models/shotgun.glb");
useGLTF.preload("assets/models/staff.glb");
useGLTF.preload("assets/models/sword.glb");
useGLTF.preload("assets/models/treasureChestClosed.glb");
useGLTF.preload("assets/models/treasureChestOpen.glb");
useGLTF.preload("assets/models/uzi.glb");
